import type { Metadata } from "next";
import UseCaseTemplate from "@/components/templates/UseCaseTemplate";
import { UseCaseConfig } from "@/lib/page-content";
import type { FaqItem } from "@/lib/live-faqs";

// DOOH · Use case (screen audience measurement / retail media).
// DOOH-specific FAQs (not the shopping-malls ones) to avoid duplicating the
// FAQPage schema of /en/solution-for-shopping-malls/.

export const metadata: Metadata = {
  title: "DOOH Measurement · Retail Media for your screens · Flame Analytics",
  description: "Measure the real audience of your DOOH screens, monetise your inventory and prove ROI to advertisers. Audited metrics, no facial recognition, on top of your existing camera network.",
  alternates: {
    canonical: "/en/dooh/",
    languages: {
      es: "/es/dooh/",
      en: "/en/dooh/",
      "x-default": "/es/dooh/",
    },
  },
  openGraph: {
    type: "website",
    url: "https://www.flameanalytics.com/en/dooh/",
    siteName: "Flame Analytics",
    title: "DOOH Measurement · Retail Media · Flame Analytics",
    description: "Measure the real audience of your DOOH screens, monetise your inventory and prove ROI to advertisers.",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "DOOH Measurement · Retail Media · Flame Analytics",
    description: "Measure the real audience of your DOOH screens, monetise your inventory and prove ROI to advertisers.",
  },
};

const DOOH_FAQS: FaqItem[] = [
  {
    q: "What is DOOH audience measurement?",
    a: "It means measuring how many people actually see each digital out-of-home (DOOH) screen, instead of estimating it. In a shopping mall or a store, that means knowing how many people walked past each screen at every time of day, how long they stayed in front of it and how many later visited the advertised store. Brands investing in retail media no longer accept estimates: they want verified audiences. Flame measures it with video analytics on top of your camera network, using aggregated and anonymous data.",
  },
  {
    q: "Which retail media metrics does Flame measure for each screen?",
    a: "The ones premium brands ask for, per campaign, screen and zone: real impressions (how many people were actually in front of each screen at every time of day), customer typology (gender and age band distribution, aggregated and anonymous), dwell time and attention (average time in front of the screen and percentage of effective attention) and drive-to-store (incremental visits to the advertised store amongst exposed vs non-exposed visitors). After every campaign you get a report ready to send to the advertiser, with the key results per screen and zone.",
  },
  {
    q: "How do I prove to a brand that its DOOH campaign drove store visits?",
    a: "With drive-to-store measurement. Flame compares visits to the advertised store between people exposed to the screen and people who were not, isolating the incremental visits generated by the campaign. You can also compare traffic and conversion across pre- and post-campaign periods, by zone or by store. It closes the loop every advertiser asks for: not just how many people saw the ad, but how many walked in afterwards.",
  },
  {
    q: "How does it help me sell my screen inventory?",
    a: "You move from selling screens to selling audiences. With an audited audience, your rate card stops relying on estimates and reflects the real value you deliver. Premium brands ask for real impressions, audience profile and drive-to-store; if your rate card can't deliver them, your inventory competes as filler. With that data per campaign, screen and zone you can justify the price of every screen and prove ROI to brands and agencies.",
  },
  {
    q: "Do I need new hardware or a different digital signage CMS?",
    a: "Usually not. Flame runs on your existing IP camera network: its Hypersensor technology connects to the video streams via RTSP and is compatible with the main brands, such as Axis, Hikvision, Dahua, Bosch and Hanwha, although results depend on camera quality, placement and calibration. It doesn't replace your digital signage CMS or your DOOH platform either: it is an analytics layer independent of the hardware and the CMS that integrates with the systems you already use, and you can export the data via API to BI tools such as Power BI, Tableau or Looker.",
  },
  {
    q: "Is it GDPR compliant? Does it use facial recognition?",
    a: "Yes, it is GDPR compliant and it does not use facial recognition. Flame does not use biometric data or identify anyone: it extracts analytical data from the video streams and discards the original images, and no video is stored outside your security system. What you get is aggregated, anonymous data that you can share with your advertisers without exposing any personal information.",
  },
];

const cfg: UseCaseConfig = {
  metaTitle: "DOOH · Flame Analytics",
  metaDescription: "Audited DOOH audience measurement and retail media analytics.",
  heroTitle: "DOOH Measurement",
  heroBgImage: "https://uryoqblopkijfqnzquhm.supabase.co/storage/v1/object/public/blog-media/landings/dooh-hero-v5.webp",
  heroBgPosition: "center center",
  heroSub: "Turn your digital screens into a real retail media business. Flame measures the audience walking past every screen, proves ROI to brands and delivers the reports you need to share verified data with your advertisers. The same rigor digital advertising already demands, applied to the physical world.",
  heroBullets: ["90+ B2B clients", "12 countries", "On top of your cameras", "No facial recognition"],
  imageBigSrc: "/wp-content/uploads/2026/01/People-Counting_recorte.png",
  imageBigAlt: "Flame Analytics DOOH measurement dashboard",
  bigSectionTitle: "From the CMS playlist to the real",
  bigSectionTitleHl: "impression",
  bigSectionPara1: "Retailers and brands investing in retail media no longer accept estimates. They want to know how many people stood in front of each screen, with what profile, and how many later visited the advertised store.",
  bigSectionPara2: "Flame turns your camera network into an audited measurement layer for your DOOH inventory. No extra hardware, no facial recognition, aggregated and anonymous data under GDPR, and integration with the main signage CMS and DOOH platforms. The venue stops selling estimated impressions and starts selling verified audience.",
  bigSectionBullets: ["Real impressions", "Drive to store", "Anonymous demographics", "Campaign reports"],
  benefitsTitle: "of measuring your DOOH",
  benefitsTitleHl: "Benefits",
  benefitsSub: "Move from selling screens to selling audiences. The difference between a retail media program that scales and a digital signage network that doesn't is whether you can prove the data.",
  benefits: [
    { icon: "trending",    title: "Raise your inventory price",                  desc: "Sell with audited audience, not estimates. Your rate card stops tracking inflation and starts tracking the real value you deliver." },
    { icon: "convert",     title: "Prove ROI to brands and agencies",            desc: "Measure visits, dwell time and movement between zones. Compare traffic and conversion across pre/post campaign periods, by zone or by store." },
    { icon: "integration", title: "Connect to DOOH and your CMS",                desc: "Analytics layer independent of the hardware and the CMS. We complement any DOOH stack and integrate with the systems you already use." },
    { icon: "privacy",     title: "No facial recognition · GDPR by design",      desc: "No facial recognition, no biometric data, fully compliant with privacy regulations such as GDPR." },
  ],
  metricsTitle: "The metrics you need to",
  metricsTitleHl: "show",
  metricsSub: "Premium brands ask for these. If your rate card can't deliver them, you stay in the filler inventory. Flame measures and reports them per campaign, screen and zone.",
  metrics: [
    { icon: "eye",          title: "Real impression measurement", desc: "How many people were actually in front of each screen at every time of day. No estimates." },
    { icon: "demographics", title: "Customer typology",           desc: "Gender and age band distribution per screen. Aggregated and anonymous, ready to report with full accuracy." },
    { icon: "dwell",        title: "Dwell time and attention",    desc: "Average time in front of the screen and percentage of effective attention. Impression quality, not just quantity." },
    { icon: "convert",      title: "Drive-to-store and lift",     desc: "Incremental visits to the advertised store amongst exposed vs non-exposed visitors. The full loop every advertiser asks for." },
    { icon: "reports",      title: "Campaign reports",            desc: "Report ready to send after every campaign, with the key results per screen and zone." },
  ],
  testimonialsIdx: [6, 3, 2],
  faqs: DOOH_FAQS,
  ctaStripBold: "Ready to turn your screens into a retail media business?",
  ctaStripLight: "Free DOOH potential audit of your venue. 30 minutes.",
};

export default function DoohEN() {
  return <UseCaseTemplate cfg={cfg} enHref="/es/dooh/" currentLang="en" />;
}
