import type { Metadata } from "next";
import UseCaseTemplate from "@/components/templates/UseCaseTemplate";
import { UseCaseConfig } from "@/lib/page-content";

export const metadata: Metadata = {
  title: "Conversion Analytics · Flame Analytics",
  description: "See your physical conversion funnel end-to-end — from street traffic to in-store engagement and final purchase. Understand what attracts, what holds attention a",
};

const cfg: UseCaseConfig = {
  metaTitle: "Conversion Analytics · Flame Analytics",
  metaDescription: "See your physical conversion funnel end-to-end — from street traffic to in-store engagement and final purchase. Understand what attracts, what holds attention a",
  heroBgImage: "/wp-content/uploads/2026/01/conversion_analytics.png",
  heroBgPosition: "center center",
  heroTitle: "Conversion Analytics",
  heroSub: "See your physical conversion funnel end-to-end — from street traffic to in-store engagement and final purchase. Understand what attracts, what holds attention and what triggers the sale.",
  heroBullets: ["Conversion funnels", "Conversion rates", "Sales insights", "Visit duration"],
  imageBigSrc: "/wp-content/uploads/2026/01/Conversion_analytics_recorte.png",
  imageBigAlt: "Flame Conversion Analytics dashboard",
  bigSectionTitle: "From raw traffic to",
  bigSectionTitleHl: "conversion decisions",
  bigSectionPara1: "Flame Conversion connects visitor analytics with sales data to visualize the full funnel — from street traffic to in-store engagement and purchases.",
  bigSectionPara2: "Analyze capture and conversion rates, dwell time and performance by zone, store or category. Turn data into action with real-time dashboards.",
  bigSectionBullets: ["Conversion funnels", "Conversion rates", "Sales insights", "Visit duration"],
  benefitsTitle: "of Conversion Analytics",
  benefitsTitleHl: "Benefits",
  benefitsSub: "Turn intuition into action plan: where to optimize, when to intervene, and what truly moves the needle.",
  benefits: [
    { icon: "journey", title: "Discover the full conversion journey", desc: "See how visitors evolve from passers-by to buyers and where the funnel leaks." },
    { icon: "eye", title: "Improve capture and retention", desc: "Find which storefronts, campaigns and hours attract more and keep them longer." },
    { icon: "dwell", title: "Leverage dwell time data", desc: "Correlate time spent with sales to fine-tune layout, staffing and promotions." },
    { icon: "trending", title: "Drive conversion and profitability", desc: "Connect traffic and behavior with POS to surface what truly drives ROI." },
  ],
  metricsTitle: "The metrics that change",
  metricsTitleHl: "decisions",
  metricsSub: "Cross visitors with operations and sales to discover actionable patterns.",
  metrics: [
    { icon: "convert", title: "Real conversion rate", desc: "Visitors vs. tickets generated. The metric that matters." },
    { icon: "clock", title: "Conversion by time slot", desc: "When you convert better and when opportunities are lost." },
    { icon: "behavior", title: "Conversion by zone", desc: "Which store areas sell and which only attract traffic." },
    { icon: "ratio", title: "Average ticket per visit", desc: "Real economic value generated by each visitor." },
    { icon: "compare", title: "Store benchmarks", desc: "Identify top-performers and replicate their practices." },
    { icon: "calendar", title: "Campaign impact", desc: "Real conversion lift during and after each promotion." },
  ],
  testimonialsIdx: [0, 1, 2, 5, 6],
  faqs: [
    { q: "How is the conversion rate calculated?", a: "Flame divides POS tickets by unique visitors counted by the cameras within a time window. Segmentable by hour, day, zone, category or salesperson." },
    { q: "Does it work with any POS?", a: "Yes. Native connectors for major systems (Toshiba, NCR, ICG, Cegid, Mistral) plus open API and scheduled CSV imports for custom setups." },
    { q: "How long until we see data?", a: "Traffic data is available 5–7 days after signing. POS integration usually adds 1–2 weeks depending on the system. Full conversion live within 30 days." },
    { q: "Can we measure conversion by product category?", a: "Yes, if your POS sends the category with each ticket. Flame correlates zone traffic (cameras) with category sales (POS) to reveal which products convert in which areas." },
    { q: "Is it GDPR compliant?", a: "Yes. Flame counts anonymous silhouettes, never personal data. POS data is crossed at aggregate time-window level, never per individual." },
    { q: "What ROI should we expect?", a: "Most retailers see 3–8% lift in conversion and 8–15% lower labor cost through smarter staffing. Payback typically under 12 months." },
  ],
  ctaStripBold: "Know your real conversion rate, not what you think it is.",
  ctaStripLight: "Personalized demo in 20 minutes.",
};

export default function ConversionAnalyticsEN() {
  return <UseCaseTemplate cfg={cfg} enHref="/es/analitica-conversion/" currentLang="en" />;
}
